# Generated by Django 3.0.3 on 2020-02-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_auto_20200227_1317'),
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trips',
            field=models.ManyToManyField(blank=True, related_name='attendees', to='trips.Trip'),
        ),
    ]
