# Generated by Django 3.0.3 on 2020-03-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_auto_20200229_2025'),
        ('jwt_auth', '0005_remove_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trip_shares',
            field=models.ManyToManyField(blank=True, related_name='_user_trip_shares_+', to='trips.Trip'),
        ),
    ]
