# Generated by Django 3.0.3 on 2020-03-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_auto_20200229_2025'),
        ('jwt_auth', '0009_auto_20200303_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trip_offers',
            field=models.ManyToManyField(blank=True, related_name='_user_trip_offers_+', to='trips.Trip'),
        ),
    ]
