# Generated by Django 3.0.3 on 2020-02-27 10:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='attendees',
            field=models.ManyToManyField(related_name='trips', to=settings.AUTH_USER_MODEL),
        ),
    ]
