# Generated by Django 3.0.3 on 2020-02-26 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attractions',
            new_name='Attraction',
        ),
        migrations.RenameModel(
            old_name='Photos',
            new_name='Photo',
        ),
        migrations.RenameModel(
            old_name='ToDos',
            new_name='ToDo',
        ),
    ]
