# Generated by Django 3.0.3 on 2020-02-27 10:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0002_trip_attendees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='completed',
        ),
        migrations.AlterField(
            model_name='trip',
            name='attendees',
            field=models.ManyToManyField(null=True, related_name='trips', to=settings.AUTH_USER_MODEL),
        ),
    ]
