# Generated by Django 3.0.3 on 2020-02-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_auto_20200227_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
