# Generated by Django 3.0.3 on 2020-02-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_auto_20200229_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='private',
        ),
        migrations.AddField(
            model_name='trip',
            name='open_trip',
            field=models.BooleanField(default=False),
        ),
    ]
